name: Generate SBOM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.x
      uses: actions/setup-python@v6
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cyclonedx-bom
    - name: Create output directory
      run: |
        mkdir ~/output

    - name: Generate SBOM
      working-directory: ./
      run: |
        python -m cyclonedx_py requirements > ~/output/sbom.json

    - uses: actions/upload-artifact@v7
      with:
        name: SBOM
        path: ~/output/sbom.json
        archive: false

    - name: Scan for vulnerabilities
      uses: anchore/scan-action@v7
      with:
        sbom: ~/output/sbom.json